#@data/values
---
findr:
    appName: findr
    imageName: findr-image
    newImageName: eu.gcr.io/integration-poolboy/findr
    serviceName: findr-service
    secretName: findr-secret
    ingressName: findr-ingress
    staticIpName: nginx-ingress-static-global-ip
    externalUrl: findr.gopoolboy.dev
    sslCertSecretName: findr-ssl-secret
    dockerfileFolder: applications/findr
    namespace: findr
    appPort: 4000
    officeIps: "78.94.91.125/32,78.35.144.135/32"
    resources:
        ram: 256Mi

    env:
        node_env: bananas
        auth0_domain: bananas
        api_identifier: bananas
        es_index_prefix: bananas
    secrets:
        es_cloud_id: bananas
        es_auth_user: bananas
        es_auth_pw: bananas
