#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")
#@ load("@ytt:struct", "struct")

#@ app = data.values.findr
#@ def getSecrets():
#@    secrets = struct.decode(app.secrets)
#@    output = {}
#@    for key in secrets:
#@        output[key.upper()] = base64.encode(secrets[key])
#@    end
#@    return output
#@ end

---
apiVersion: v1
kind: Secret
metadata:
  name: #@ app.secretName
type: Opaque
data: #@ getSecrets()
