version: '3'

services:
  db-pg:
    image: postgres:12.2
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  backend:
    build: backend
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    environment:
      SECRET_KEY: "blub"
      PG_USER: postgres
      PG_PASSWORD: postgres
      PG_HOST: db-pg
      PG_PORT: 5432
    depends_on:
      - db-pg