version: '3'

services:
  db-pg:
    image: postgres:12.2
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  backend:
    build: backend
    volumes:
      - ./backend:/code
    ports:
      - 8000:8000
    environment:
      SECRET_KEY: "blub"
      PG_USER: postgres
      PG_PASSWORD: postgres
      PG_HOST: db-pg
      PG_PORT: 5432
    depends_on:
      - db-pg
  frontend:
    build: frontend
    volumes:
      - ./frontend:/app
    ports:
      - 8080:8080