version: '3'

services:
  pg-qapp:
    image: postgres:12.2
    environment:
      - POSTGRES_DB=qapp
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  qapp:
    build: qapp
    volumes:
      - ./qapp:/app
    ports:
      - 4000:4000
    depends_on:
      - pg-qapp
    environment:
      AUTH0_DOMAIN: dev-poolboy.eu.auth0.com
      API_IDENTIFIER: http://dev-poolboy-api
      DB_HOST: pg-qapp
      DB_DATABASE: qapp
      DB_USER: postgres
      DB_PASSWORD: postgres
  frontend:
    build: frontend
    volumes:
      - ./frontend:/app
    ports:
      - 8080:8080