controller:
    autoscaling:
        enabled: true
        minReplicas: 1
        maxReplicas: 2
        targetCPUUtilizationPercentage: 75
        targetMemoryUtilizationPercentage: 75

    service:
        loadBalancerIP: "34.107.36.183" # from nginx-ingress-static-ip
        loadBalancerSourceRanges: []
        externalTrafficPolicy: "Local"
        type: LoadBalancer
