#@data/values
---
qapp:
    appName: qapp
    imageName: qapp-image
    serviceName: qapp-service
    secretName: qapp-secret
    ingressName: qapp-ingress
    staticIpName: nginx-ingress-static-global-ip
    externalUrl: qapp.gopoolboy.dev
    sslCertSecretName: qapp-ssl-secret
    dockerfileFolder: applications/qapp
    namespace: qapp
    appPort: 4000
    officeIps: "78.94.91.125/32"

    env:
        auth0_domain: dev-poolboy.eu.auth0.com
        api_identifier: http://dev-poolboy-api
        db_host: pg-qapp
        db_database: qapp
    secrets:
        db_user: postgres
        db_password: postgres
