#@data/values
---
orgamon:
  appName: orgamon
  imageName: orgamon-image
  newImageName: eu.gcr.io/integration-poolboy/orgamon
  serviceName: orgamon-service
  secretName: orgamon-secret
  ingressName: orgamon-ingress
  staticIpName: nginx-ingress-static-global-ip
  externalUrl: orgamon.gopoolboy.dev
  sslCertSecretName: orgamon-ssl-secret
  dockerfileFolder: applications/orgamon
  namespace: orgamon
  appPort: 4000
  officeIps: "78.94.91.126/32,78.94.91.125/32"
  resources:
    ram: 256Mi

  env:
    node_env: production
    auth0_domain: dev-poolboy.eu.auth0.com
    api_identifier: http://dev-poolboy-api
    db_host: pg-orgamon
    db_database: orgamon
    auth0_connection_name: "Username-Password-Authentication"
  secrets:
    db_user: orgamon
    db_password: postgres
    auth0_client_id: "AUTH0_CLIENT_ID"
    auth0_client_secret: "AUTH0_CLIENT_SECRET"
