#@ load("@ytt:data", "data")
#@ load("@ytt:struct", "struct")

#@ app = data.values.findrUpdater
#@ appName = app.appName
#@ env = struct.decode(app.env)
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
    name: #@ appName
    namespace: #@ app.namespace
    labels:
        name: #@ appName
spec:
    replicas: 1
    selector:
        matchLabels:
            name: #@ appName
    template:
        metadata:
            name: #@ appName
            labels:
                name: #@ appName
        spec:
            containers:
                - name: #@ appName
                  image: #@ app.imageName
                  resources:
                      requests:
                          memory: #@ app.resources.ram
                      limits:
                          memory: #@ app.resources.ram
                  env:
                      - name: NODE_ENV
                        value: production
                      #@ for key in env:
                      - name: #@ key.upper()
                        value: #@ env[key]
                      #@ end
                  envFrom:
                      - secretRef:
                            name: #@ app.secretName
