query GetCrumb($id: ID!) {
    getCrumb(id: $id) {
        id
        title
        text
        type
        source
        votes
        ownVote
        createdAt
        authorId
        tags {
            key
            value
        }
    }
}
