query GetOrgaUsers {
    getUsers {
        id
        name
        nickname
        email
        emailVerified
        picture
        organization
        organizationRole
        lastLogin
        createdAt
        loginCount
    }
}
