query GetQuestion($questionId: ID!) {
    getQuestion(id: $questionId) {
        id
        title
        text
        votes
        createdAt
        authorId
        answers {
            id
        }
    }
}
