#@data/values
---
crumbler:
    appName: crumbler
    imageName: crumbler-image
    newImageName: eu.gcr.io/integration-poolboy/crumbler
    serviceName: crumbler-service
    secretName: crumbler-secret
    ingressName: crumbler-ingress
    staticIpName: nginx-ingress-static-global-ip
    externalUrl: crumbler.gopoolboy.dev
    sslCertSecretName: crumbler-ssl-secret
    dockerfileFolder: applications/crumbler
    namespace: crumbler
    appPort: 4000
    officeIps: "78.94.91.125/32"

    env:
        node_env: production
        auth0_domain: dev-poolboy.eu.auth0.com
        api_identifier: http://dev-poolboy-api
        db_host: pg-crumbler
        db_database: crumbler
    secrets:
        db_user: crumbler
        db_password: postgres
