#@ load("@ytt:data", "data")
#@ app = data.values.qapp

---
apiVersion: kbld.k14s.io/v1alpha1
kind: Sources
sources:
    - image: #@ app.imageName
      path: #@ app.dockerfileFolder

---
apiVersion: kbld.k14s.io/v1alpha1
kind: ImageDestinations
destinations:
    - image: #@ app.imageName
      newImage: eu.gcr.io/integration-poolboy/qapp
