# This workflow will build a docker container, publish it to Google Container Registry, and deploy it to GKE.
name: Deploy cert-manager

on:
    push:
        branches:
            - master
        paths:
            - "infrastructure/kubernetes/cert-manager/**"
            - ".github/workflows/cert-manager.yaml"

env:
    GKE_PROJECT: staging-poolboy
    GKE_ZONE: europe-west3-b
    GKE_CLUSTER: kubernetes-cluster
    YTT_VERSION: v0.27.2
    KAPP_VERSION: v0.27.0
    KBLD_VERSION: v0.22.0
    GCP_VERSION: "293.0.0"

jobs:
    deploy-cert-manager-staging:
        name: Deploy cert-manager staging
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
              with:
                  version: ${{ env.GCP_VERSION }}
                  project_id: ${{ env.GKE_KEY }}
                  service_account_key: ${{ secrets.GKE_KEY }}
                  export_default_credentials: true
            - run: |
                  gcloud auth configure-docker

            - name: Deploy via kubectl apply
              run: |
                  gcloud container clusters get-credentials $GKE_CLUSTER --zone $GKE_ZONE --project $GKE_PROJECT
                  kubectl apply -f infrastructure/kubernetes/cert-manager/cert-manager.yaml -n cert-manager
                  kubectl apply -f infrastructure/kubernetes/cert-manager/letsencrypt-staging.yaml -n cert-manager
                  kubectl apply -f infrastructure/kubernetes/cert-manager/letsencrypt-prod.yaml -n cert-manager
